### PR TITLE
Basic Ace editor integration 

### PR DESCRIPTION
**Pull request by RyanZim**
Not happy with the styling yet. Attn: @sylvainpolletvillard

### CODE REVIEW

**Comment by RyanZim** [comment]
Here's a temporary published site for this branch: http://postcss-repl-21.surge.sh/

I don't like the way the input and output isn't aligned. The output box has padding which puts the first line lower than the first line of the input. However, it doesn't look right if I remove the padding.

**Comment by sylvainpolletvillard** [comment]
What do you think of using Ace editor on the output too, with Editor#setReadonly ? It would solve the styling problems, and some features of Ace could still be useful like syntax highlight and vertical cursors.

**Comment by RyanZim** [comment]
@sylvainpolletvillard I actually tried that, but the cursor and active line was still visible, which looked weird.

**Comment by sylvainpolletvillard** [comment]
Highlight active line can be disabled, it's an option. I don't know what you mean about the cursor, why wouldn't you want it ?

**Comment by RyanZim** [comment]
Active line highlighting still highlights the gutter, even when it's disabled. The cursor looks weird and it causes bracket matching highlighting. Screenshot with readonly turned on and line highlighting turned off:

2018-01-23-103355_1680x1050_scrot

**Comment by sylvainpolletvillard** [comment]
I don't see a problem with that. How would you select text in the output if you don't have a cursor ?

**Comment by RyanZim** [comment]
The same as you'd do to select normal text on any webpage. For clarity, I'm referring to the black cursor line on the end of line 3 in the screenshot, not the mouse cursor.

**Comment by sylvainpolletvillard** [comment]
Sure I understood, but as far as I can tell, what you describe is the normal behaviour of a textarea and could be nice to have in the output zone rather than "just normal text", in my opinion. I need to check out your branch and see by myself what do you find weird here.

**Comment by RyanZim** [comment]
@sylvainpolletvillard ping?

**Comment by sylvainpolletvillard** [comment]
Hey, sorry for the delay. Check out https://github.com/RyanZim/postcss-repl/pull/22

**Pull request merged**
