### PR TITLE
Add postcss-preset-env

### LINKED ISSUE #15: Add postcss-preset-env
https://github.com/jonathantneal/postcss-preset-env

### PR DESCRIPTION
**Pull request by RyanZim**
Needs to be added to postcss-plugins first

Resolves #15

### CODE REVIEW

**Comment by RyanZim** [comment]
PR to postcss-plugins: https://github.com/himynameisdave/postcss-plugins/pull/233

**Comment by sylvainpolletvillard** [comment]
Should we think about how to configure plugins from the REPL itself ? This would be useful for this plugin in particular. I put the config property in the generated plugins.json file with this in mind.

**Comment by RyanZim** [comment]
postcss-plugins 1.11.0 contains the stuff we need.

**Comment by RyanZim** [comment]
Requires a hack in the webpack config to work around https://github.com/jonathantneal/postcss-preset-env/issues/12.

**Pull request merged**
