### PR TITLE
Design overhaul

### PR DESCRIPTION
**Pull request by sylvainpolletvillard**
Hey, so here is a first draft of the promised design overhaul

The base color is taken from Babel REPL, then I generated a palette with mycolor.space:
```
$light1: #CACFD7;
$light2: #E1E5E8;
$light3: #F3FAFF;
$dark1: #21252b;
$dark2: #2B3B50;
$dark3: #4D5258;
```

The font is Fira Sans, taken from PostCSS official website.

Other changes imply some tweaks to font sizes and to the drawer layout.

Screenshot:
image

### CODE REVIEW

**Comment by RyanZim** [comment]
@sylvainpolletvillard Why 72b54abbe78fcd01e419a206a814ec3b03e116f6 when we're not using that data at all in the client? That's just extra data being passed to the browser.

**Comment by sylvainpolletvillard** [comment]
This could be used in a future PR, see gitter conversation

**Comment by RyanZim** [comment]
Sure, I'm fine with it if it's used, but I don't want it added until the PR that actually uses it.

**Comment by sylvainpolletvillard** [comment]
Actually it fixes a bug, the description was missing in the plugins title attribute

**Comment by RyanZim** [comment]
Ah, good catch. All the same, I'd rather not pass tags, author, & stars yet.

**Comment by RyanZim** [comment]
I was going to merge this in, but I took it for a spin and text wrapping is broken:

2018-07-25-204248_1680x1024_scrot

After that's fixed, we should be good to go.

**Comment by sylvainpolletvillard** [comment]
should be fixed now

**Pull request merged**
