### PR TITLE
process PostCSS in svelte components scoped styles

### LINKED ISSUE #43: Move all CSS to svelte components
Refs https://github.com/RyanZim/postcss-repl/pull/41#issuecomment-376181687.

I'll do this after #42 gets merged. @sylvainpolletvillard you're aware that svelte scopes styles, correct?

### PR DESCRIPTION
**Pull request by sylvainpolletvillard**
fixes #43

### CODE REVIEW

**Comment by RyanZim** [comment]
This is one way of doing it. I was thinking of going the webpack route; i.e. have svelte loader `emitCSS`, then use `postcss-loader` to process it. The other concern with this approach is that I'm almost certain there's duplication here due to postcss-normalize.

**Comment by sylvainpolletvillard** [comment]
I don't think svelte is able to put scoped styles on PostCSS format. That's why it is in the "preprocess" section, because the processing has to be done before svelte goes into it and add its magic classes.

**Comment by RyanZim** [comment]
@sylvainpolletvillard Good point, you're thinking deeper than me here :wink: OK, will try this out.

**Comment by sylvainpolletvillard** [comment]
Regarding postcss-normalize, I think Jonathan solved this problem by explicitely requiring a `@import-normalize;` annotation

**Comment by RyanZim** [comment]
@sylvainpolletvillard Fixed normalize duplication.

One more bikeshedding point: Right now, the codemirror CSS is getting scoped, which does expand it's size slightly. We might get better perf by putting that in the global app CSS. Not sure if it's worth it, though.

**Comment by sylvainpolletvillard** [comment]
Sure, feel free to move it to index.css file

**Comment by RyanZim** [comment]
@sylvainpolletvillard Done.

**Pull request merged**
