### PR TITLE
Switch to codemirror for decent syntax highlighting

### PR DESCRIPTION
**Pull request by RyanZim**
Demo live at http://new-mom.surge.sh/

@sylvainpolletvillard @ai how does it look?

### CODE REVIEW

**Comment by sylvainpolletvillard** [comment]
I can't tell the difference in terms of features between Ace and Codemirror. Did you change because the syntax highlighting was not advanced enough ?

Regarding the syntax highlight color theme, may I suggest to choose one with more contrast ? I am slightly color blind and I almost thought the syntax highlight was not working at all. I had to zoom in and check the HTML classes to be sure 👀

**Comment by RyanZim** [comment]
@sylvainpolletvillard Ace's CSS syntax highlighting was very brittle, and didn't know how to handle modern CSS proposed features. Codemirror's highlighting is way better IMO.

> Regarding the syntax highlight color theme, may I suggest to choose one with more contrast ? I am slightly color blind and I almost thought the syntax highlight was not working at all.

**Comment by sylvainpolletvillard** [comment]
Maybe we should open another issue to discuss about the theme. Personally I use light themes at daytime and dark themes at night. This is what gives me the best results in terms of readability and eye fatigue.

**Comment by RyanZim** [comment]
@sylvainpolletvillard Agreed. I'll merge this first, then we can build on that.

**Pull request merged**
